// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_main_page: dynamic(() => import("./AboutMainPage")),
  column_heading_button: dynamic(() => import("./ColumnHeadingButton")),
  gallery_slice: dynamic(() => import("./GallerySlice")),
  heading_content_button: dynamic(() => import("./HeadingContentButton")),
  hero: dynamic(() => import("./Hero")),
  muted_info_cards: dynamic(() => import("./MutedInfoCards")),
  sticky_column: dynamic(() => import("./StickyColumn")),
  text_block: dynamic(() => import("./TextBlock")),
};
