// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_main_page: dynamic(() => import("./AboutMainPage")),
  gallery_slice: dynamic(() => import("./GallerySlice")),
  hero: dynamic(() => import("./Hero")),
  text_block: dynamic(() => import("./TextBlock")),
};
