import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import clsx from "clsx";
import { ThemeProvider } from "@/components/theme-provider";
import { syne, inter } from "./font";
import Footer from "@/components/Footer";
import MobileNavSheet from "@/components/MobileNavSheet";
import DesktopSidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable,
          syne.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <main className="grid min-h-screen w-full md:grid-cols-[240px_1fr]">
            <div className="fixed bottom-6 left-6 z-30 md:hidden">
              <MobileNavSheet />
            </div>
            <DesktopSidebar />
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
